### ISSUE TITLE
SEO: Structured Data

### ISSUE THREAD

**Issue by grctest** [cyberpunk-ventures/glasnost#10]
So I've been improving the SEO of my blog with simple meta tags, but we could potentially implement structured data within the post template in order to get glasnost steemit posts indexed like news articles and displayed directly in google: https://developers.google.com/search/docs/guides/?hl=en-GB https://developers.google.com/search/docs/data-types/articles?hl=en-GB

What do you think? I'm going to give it a try.

Annoyances with AMP:
* Potentially need to convert css to inline..
* May need to replace html tags

---

Edit: AMP is too disruptive.

**Comment by grctest** [comment]
So I chose to use JSON-LD rather than microcode (too inline with code) and AMP (would require changes to the raw body text & all css).

On pages I put the following at the bottom:
```
<script type="application/ld+json">
{ "@context": "http://schema.org", 
 "@type": "Article",
 "headline": "<%= @post.title %>",
 "alternativeHeadline": "<%= @post.title %>",
 "image": "https://beyondboinc.net/images/steem-logo.png",
 "author": "<%= @post.author %>", 
 "editor": "<%= @post.author %>", 
 "genre": "<%= for tag <- @post.tags do %><%=tag%> <% end %>", 
 "keywords": "<%= for tag <- @post.tags do %><%=tag%> <% end %>", 
 "publisher": "Steemit",
 "url": "https://beyondboinc.net/authors/<%= @post.author %>/<%= @post.permlink %>/",
 "description": "<%= @post.title %>",
 "articleBody": "<%= raw(@post.body) %>"
 }
</script>
```

The above means that every post will have the appropriate SEO data autogenerated.

Related to the above, if we can get 

If we can convert the post timestamp to YYYY-MM-DD we can add the following (good for date filtering)
```"datePublished": "2015-09-20",
 "dateCreated": "2015-09-20",
 "dateModified": "2015-09-20",
```

I caused an internal error trying to create an if/else function for the image SEO tag:
  "image": "<%= if @img_src do %><%= @img_src %><% end %> || https://beyondboinc.net/images/steem-logo.png"

The idea for the above is that if there is a pic present, it'll use that otherwise it'll use the website's logo.

---

On the main index page I put:
<script type='application/ld+json'> 
{
  "@context": "http://www.schema.org",
  "@type": "WebSite",
  "name": "BeyondBOINC",
  "alternateName": "BeyondBoinc",
  "url": "https://beyondboinc.net"
}
 </script>

**Comment by grctest** [comment]
>Another SEO idea that's potentially a good idea is generating a full sitemap.xml for search engine crawlers to index. It'd be a pretty large file though.

To generate a full sitemap.xml:
```
npm install -g sitemap-generator-cli
sitemap-generator https://beyondboinc.net /glasnost_app/_build/prod/lib/glasnost/priv/static/sitemap.xml
```

**Comment by ontofractal** [comment]
Glasnost has evolved to become a GraphQL app server, HTML pipeline was removed and this issue is no longer relevant.
