### ISSUE TITLE
Images not rendering in post

### ISSUE THREAD

**Issue by grctest** [cyberpunk-ventures/glasnost#11]
Currently only the image's URL is shown as opposed to being encapsulated with the <img src="" /> tags.

**Comment by grctest** [comment]
It looks like it's just the markdown images that it doesn't like, if the user uses html tags <img src=""> it will render currently.

ex:
![image](https://cloud.githubusercontent.com/assets/15861527/25317358/2483d836-286f-11e7-9255-06f71f7bb6f4.png)

**Comment by ontofractal** [comment]
should work as expected now!
