### ISSUE TITLE
Too many images overwhelms image selection for posts card view?

### ISSUE THREAD

**Issue by grctest** [cyberpunk-ventures/glasnost#13]
![image](https://cloud.githubusercontent.com/assets/15861527/25383938/219bad68-29b6-11e7-879a-6689ffe9e905.png)

Example page:
https://beyondboinc.net/authors/screenname/the-daily-tribune-most-undervalued-posts-of-apr-24---part-ii
https://steemit.com/@screenname/the-daily-tribune-most-undervalued-posts-of-apr-24---part-ii

It has a main image (used as thumbnail on steemit) then ~80-100 mini thumbnails for the highlighted posts.

Think that no image is being shown in the posts page because of the quantity of images to pick from?

**Comment by grctest** [comment]
> <% img_src = hd(post.json_metadata["image"] || post.json_metadata["images"] || [false] ) %>
The above is used for displaying an image in the posts card overview.

Looking into the screenname's posts, the post json data is:
>"{"tags": ["stats", "steemit", "tribune"]}"

No images in the post json metadata..

**Comment by ontofractal** [comment]
posts will now have a default image
