### ISSUE TITLE
Markdown tables not rendering

### ISSUE THREAD

**Issue by grctest** [cyberpunk-ventures/glasnost#14]
On BeyondBoinc:
![image](https://cloud.githubusercontent.com/assets/15861527/25458809/5ba02caa-2ad3-11e7-8ae0-6bebe7d4b713.png)

https://beyondboinc.net/authors/steempower/bitshares-state-of-the-network-25th-april-2017

On Steemit:
![image](https://cloud.githubusercontent.com/assets/15861527/25458831/75cc9e42-2ad3-11e7-90a1-f877a75419d6.png)

https://steemit.com/bitshares/@steempower/bitshares-state-of-the-network-25th-april-2017

**Comment by ontofractal** [comment]
Glasnost has evolved to become a GraphQL app server, HTML pipeline was removed and this issue is no longer relevant.
