### ISSUE TITLE
Маркдаун режет страницы с кодами html

### ISSUE THREAD

**Issue by vadbars** [cyberpunk-ventures/glasnost#4]
Если встречается код html, например `<li>`, страница обрезается. а код выводится на страницу. Пример: https://golos.io/mapala/@vadbars/bolgarskiij-voyazh-2010-trudnoe-nachalo
Текст не выводится совсем. После картинки сразу
` <li>Трудное начало  <a href="https://golos.io/mapala/@vadbars/bolgarskiij-voyazh-2010-trudnoe-nachalo" target="_blank">Голос</a>, <a href="http://mapala.net/vadbars/bolgarskiij-voyazh-2010-trudnoe-nachalo" target="_blank">Мапала</a></li>
	<li>Краснокожая паспортина и все, все, все  <a href="https://golos.io/mapala/@vadbars/bolgarskiij-voyazh-krasnokozhaya-pasportina-i-vse-vse-vse" target="_blank">Голос</a>, <span></span><a href="http://mapala.net/vadbars/bolgarskiij-voyazh-krasnokozhaya-pasportina-i-vse-vse-vse" target="_blank">Мапала</a></li>`

**Comment by ontofractal** [comment]
Спасибо, в работе. Скорее всего необходимо использование нового модуля для парсинга маркдауна.

При возможности, issues и pull requests лучше на английском.

**Comment by vadbars** [comment]
Понял про ангельский. ) Буду.

**Comment by ontofractal** [comment]
Glasnost больше не отдает статические страницы
