### ISSUE TITLE
Error while starting Glasnost app in Docker

### ISSUE THREAD

**Issue by leagueofdelegates** [cyberpunk-ventures/glasnost#5]
C:\Users\User>docker run -it -p 80:80 -e "GLASNOST_CONFIG_URL=C:\Users\User\config.json"  --restart on-failure:10 ontofractal/glasnost:latest
22:00:59.750 [error] ** State machine #PID<0.194.0> terminating
** Last message in was {:ssl,
 {:sslsocket, {:gen_tcp, #Port<0.6684>, :tls_connection, :undefined},
  #PID<0.199.0>},
 "HTTP/1.1 502 Bad Gateway\r\nServer: nginx/1.10.0 (Ubuntu)\r\nDate: Thu, 30 Mar 2017 22:00:45 GMT\r\nContent-Type: text/html\r\nContent-Length: 174\r\nConnection: keep-alive\r\n\r\n<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.11.10</center>\r\n</body>\r\n</html>\r\n"}
** When State == :handshaking
**      Data  == {:context,
 {:websocket_req, :wss, 'ws.golos.io', 443, '/', :infinity, :undefined, 1,
  {:sslsocket, {:gen_tcp, #Port<0.6684>, :tls_connection, :undefined},
   #PID<0.199.0>},
  {:transport, :ssl, :ssl, :ssl_closed, :ssl_error,
   [mode: :binary, active: true, verify: :verify_none, packet: 0]},
  "v2RSnWyWQKbsisDacXuHNw==", :undefined, :undefined, :undefined, :undefined,
  :undefined},
 {:transport, :ssl, :ssl, :ssl_closed, :ssl_error,
  [mode: :binary, active: true, verify: :verify_none, packet: 0]}, [],
 {:wss, 'ws.golos.io', 443, '/'}, {Golos.WS, %{}}, "", false, 0}
** Reason for termination =
** {:function_clause,
 [{Golos.WS, :ondisconnect, [{:error, {502, "Bad Gateway"}}, %{}],
   [file: 'lib/ex_golos/golos_ws.ex', line: 29]},
  {:websocket_client, :disconnect, 2,
   [file: '/glasnost_app/deps/websocket_client/src/websocket_client.erl',
    line: 277]}, {:gen_fsm, :handle_msg, 7, [file: 'gen_fsm.erl', line: 451]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}

22:01:00.042 [error] ** State machine #PID<0.228.0> terminating
** Last message in was {:ssl,
 {:sslsocket, {:gen_tcp, #Port<0.8031>, :tls_connection, :undefined},
  #PID<0.234.0>},
 "HTTP/1.1 502 Bad Gateway\r\nServer: nginx/1.10.0 (Ubuntu)\r\nDate: Thu, 30 Mar 2017 22:00:46 GMT\r\nContent-Type: text/html\r\nContent-Length: 174\r\nConnection: keep-alive\r\n\r\n<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.11.10</center>\r\n</body>\r\n</html>\r\n"}
** When State == :handshaking
**      Data  == {:context,
 {:websocket_req, :wss, 'ws.golos.io', 443, '/', :infinity, :undefined, 1,
  {:sslsocket, {:gen_tcp, #Port<0.8031>, :tls_connection, :undefined},
   #PID<0.234.0>},
  {:transport, :ssl, :ssl, :ssl_closed, :ssl_error,
   [mode: :binary, active: true, verify: :verify_none, packet: 0]},
  "DK6O0zqie/8XdjDJT1I24w==", :undefined, :undefined, :undefined, :undefined,
  :undefined},
 {:transport, :ssl, :ssl, :ssl_closed, :ssl_error,
  [mode: :binary, active: true, verify: :verify_none, packet: 0]}, [],
 {:wss, 'ws.golos.io', 443, '/'}, {Golos.WS, %{}}, "", false, 0}
** Reason for termination =
** {:function_clause,
 [{Golos.WS, :ondisconnect, [{:error, {502, "Bad Gateway"}}, %{}],
   [file: 'lib/ex_golos/golos_ws.ex', line: 29]},
  {:websocket_client, :disconnect, 2,
   [file: '/glasnost_app/deps/websocket_client/src/websocket_client.erl',
    line: 277]}, {:gen_fsm, :handle_msg, 7, [file: 'gen_fsm.erl', line: 451]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}

22:01:00.482 [info] Running Glasnost.Web.Endpoint with Cowboy using http://:::80
22:01:00.575 [error] ** State machine #PID<0.287.0> terminating
** Last message in was {:ssl,
 {:sslsocket, {:gen_tcp, #Port<0.10193>, :tls_connection, :undefined},
  #PID<0.295.0>},
 "HTTP/1.1 502 Bad Gateway\r\nServer: nginx/1.10.0 (Ubuntu)\r\nDate: Thu, 30 Mar 2017 22:00:46 GMT\r\nContent-Type: text/html\r\nContent-Length: 174\r\nConnection: keep-alive\r\n\r\n<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.11.10</center>\r\n</body>\r\n</html>\r\n"}
** When State == :handshaking
**      Data  == {:context,
 {:websocket_req, :wss, 'ws.golos.io', 443, '/', :infinity, :undefined, 1,
  {:sslsocket, {:gen_tcp, #Port<0.10193>, :tls_connection, :undefined},
   #PID<0.295.0>},
  {:transport, :ssl, :ssl, :ssl_closed, :ssl_error,
   [mode: :binary, active: true, verify: :verify_none, packet: 0]},
  "sd6wqfbQLONfRAp4VCsKcA==", :undefined, :undefined, :undefined, :undefined,
  :undefined},
 {:transport, :ssl, :ssl, :ssl_closed, :ssl_error,
  [mode: :binary, active: true, verify: :verify_none, packet: 0]}, [],
 {:wss, 'ws.golos.io', 443, '/'}, {Golos.WS, %{}}, "", false, 0}
** Reason for termination =
** {:function_clause,
 [{Golos.WS, :ondisconnect, [{:error, {502, "Bad Gateway"}}, %{}],
   [file: 'lib/ex_golos/golos_ws.ex', line: 29]},
  {:websocket_client, :disconnect, 2,
   [file: '/glasnost_app/deps/websocket_client/src/websocket_client.erl',
    line: 277]}, {:gen_fsm, :handle_msg, 7, [file: 'gen_fsm.erl', line: 451]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}

22:01:00.706 [info] Application glasnost exited: Glasnost.Application.start(:normal, []) returned an error: shutdown: failed to start child: Glasnost.Orchestrator.AuthorSyncSup
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            :erlang.list_to_integer('\\Users\\User\\config.json')
            (hackney) /glasnost_app/deps/hackney/src/hackney_url.erl:204: :hackney_url.parse_netloc/2
            (hackney) /glasnost_app/deps/hackney/src/hackney.erl:346: :hackney.request/5
            (httpoison) lib/httpoison/base.ex:432: HTTPoison.Base.request/9
            (glasnost) lib/glasnost/runtime_config.ex:57: RuntimeConfig.fetch_external_config/0
            (con_cache) lib/con_cache/operations.ex:202: ConCache.Operations.dirty_get_or_store/3
            (con_cache) lib/con_cache/lock.ex:31: ConCache.Lock.exec/4
            (glasnost) lib/glasnost/runtime_config.ex:11: RuntimeConfig.get/1
{"Kernel pid terminated",application_controller,"{application_start_failure,glasnost,{{shutdown,{failed_to_start_child,'Elixir.Glasnost.Orchestrator.AuthorSyncSup',{badarg,[{erlang,list_to_integer,[\"\\Users\\User\\config.json\"],[]},{hackney_url,parse_netloc,2,[{file,\"/glasnost_app/deps/hackney/src/hackney_url.erl\"},{line,204}]},{hackney,request,5,[{file,\"/glasnost_app/deps/hackney/src/hackney.erl\"},{line,346}]},{'Elixir.HTTPoison.Base',request,9,[{file,\"lib/httpoison/base.ex\"},{line,432}]},{'Elixir.RuntimeConfig',fetch_external_config,0,[{file,\"lib/glasnost/runtime_config.ex\"},{line,57}]},{'Elixir.ConCache.Operations',dirty_get_or_store,3,[{file,\"lib/con_cache/operations.ex\"},{line,202}]},{'Elixir.ConCache.Lock',exec,4,[{file,\"lib/con_cache/lock.ex\"},{line,31}]},{'Elixir.RuntimeConfig',get,1,[{file,\"lib/glasnost/runtime_config.ex\"},{line,11}]}]}}},{'Elixir.Glasnost.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,glasnost,{{shutdown,{failed_to_start_child,'Elixir.Glasnost.Orchestrator.AuthorSyncSup',{badarg,[{erlang,list_to_integer,["\\

Crash dump is being written to: erl_crash.dump...done

C:\Users\User>|

**Comment by ontofractal** [comment]
This seems to be a temporary issue related to the current public Golos websocket endpoint (wss://ws.golos.io) outage. You can use your own Golos node by changing the `GOLOS_URL` environment variable in the .Dockerfile and building your image.

**Comment by leagueofdelegates** [comment]
Now i geting this....

C:\Users\User>docker run -it -p 80:80 -e "GLASNOST_CONFIG_URL=C:\Users\User\config.json"  --restart on-failure:10 ontofractal/glasnost:latest
22:08:50.626 [info] Running Glasnost.Web.Endpoint with Cowboy using http://:::80
22:08:50.833 [info] Application glasnost exited: Glasnost.Application.start(:normal, []) returned an error: shutdown: failed to start child: Glasnost.Orchestrator.AuthorSyncSup
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            :erlang.list_to_integer('\\Users\\User\\config.json')
            (hackney) /glasnost_app/deps/hackney/src/hackney_url.erl:204: :hackney_url.parse_netloc/2
            (hackney) /glasnost_app/deps/hackney/src/hackney.erl:346: :hackney.request/5
            (httpoison) lib/httpoison/base.ex:432: HTTPoison.Base.request/9
            (glasnost) lib/glasnost/runtime_config.ex:57: RuntimeConfig.fetch_external_config/0
            (con_cache) lib/con_cache/operations.ex:202: ConCache.Operations.dirty_get_or_store/3
            (con_cache) lib/con_cache/lock.ex:31: ConCache.Lock.exec/4
            (glasnost) lib/glasnost/runtime_config.ex:11: RuntimeConfig.get/1
{"Kernel pid terminated",application_controller,"{application_start_failure,glasnost,{{shutdown,{failed_to_start_child,'Elixir.Glasnost.Orchestrator.AuthorSyncSup',{badarg,[{erlang,list_to_integer,[\"\\Users\\User\\config.json\"],[]},{hackney_url,parse_netloc,2,[{file,\"/glasnost_app/deps/hackney/src/hackney_url.erl\"},{line,204}]},{hackney,request,5,[{file,\"/glasnost_app/deps/hackney/src/hackney.erl\"},{line,346}]},{'Elixir.HTTPoison.Base',request,9,[{file,\"lib/httpoison/base.ex\"},{line,432}]},{'Elixir.RuntimeConfig',fetch_external_config,0,[{file,\"lib/glasnost/runtime_config.ex\"},{line,57}]},{'Elixir.ConCache.Operations',dirty_get_or_store,3,[{file,\"lib/con_cache/operations.ex\"},{line,202}]},{'Elixir.ConCache.Lock',exec,4,[{file,\"lib/con_cache/lock.ex\"},{line,31}]},{'Elixir.RuntimeConfig',get,1,[{file,\"lib/glasnost/runtime_config.ex\"},{line,11}]}]}}},{'Elixir.Glasnost.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,glasnost,{{shutdown,{failed_to_start_child,'Elixir.Glasnost.Orchestrator.AuthorSyncSup',{badarg,[{erlang,list_to_integer,["\\

Crash dump is being written to: erl_crash.dump...done

**Comment by leagueofdelegates** [comment]
Can i try it on steem chain?

**Comment by ontofractal** [comment]
Glasnost automatically connects both to Steem and Golos, so if you don't want to deploy your own Golos node, just wait for while.

But you can choose a source blockchainfor posts in the config file. The config file should be uploaded to the remote host like [pastebin](pastebin.com), not served from a local file system. That's the reason for your last error.

**Comment by leagueofdelegates** [comment]
Same like last time...


C:\Users\User>docker run -it -p 80:80 -e "GLASNOST_CONFIG_URL=https://pastebin.com/6ywzznh2"  --restart on-failure:10 ontofractal/glasnost:latest
22:24:23.837 [info] Running Glasnost.Web.Endpoint with Cowboy using http://:::80
22:24:24.788 [info] Application glasnost exited: Glasnost.Application.start(:normal, []) returned an error: shutdown: failed to start child: Glasnost.Orchestrator.AuthorSyncSup
    ** (EXIT) an exception was raised:
        ** (BadMapError) expected a map, got: {:error, {:invalid, "<"}}
            (stdlib) :maps.find(:authors, {:error, {:invalid, "<"}})
            (elixir) lib/map.ex:234: Map.get/3
            (glasnost) lib/glasnost/runtime_config.ex:11: RuntimeConfig.get/1
            (glasnost) lib/glasnost/blockchain/sync_orchestrator.ex:13: Glasnost.Orchestrator.AuthorSyncSup.init/1
            (stdlib) supervisor.erl:294: :supervisor.init/1
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
{"Kernel pid terminated",application_controller,"{application_start_failure,glasnost,{{shutdown,{failed_to_start_child,'Elixir.Glasnost.Orchestrator.AuthorSyncSup',{{badmap,{error,{invalid,<<\"<\">>}}},[{maps,find,[authors,{error,{invalid,<<\"<\">>}}],[]},{'Elixir.Map',get,3,[{file,\"lib/map.ex\"},{line,234}]},{'Elixir.RuntimeConfig',get,1,[{file,\"lib/glasnost/runtime_config.ex\"},{line,11}]},{'Elixir.Glasnost.Orchestrator.AuthorSyncSup',init,1,[{file,\"lib/glasnost/blockchain/sync_orchestrator.ex\"},{line,13}]},{supervisor,init,1,[{file,\"supervisor.erl\"},{line,294}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,247}]}]}}},{'Elixir.Glasnost.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,glasnost,{{shutdown,{failed_to_start_child,'Elixir.Glasnost.Orchestrator.AuthorSyncSup',{{badmap,{error,{invalid,<<"<">>}}},[

Crash dump is being written to: erl_crash.dump...done

**Comment by ontofractal** [comment]
you need a raw link to the file, like this: https://pastebin.com/raw/6ywzznh2

**Comment by leagueofdelegates** [comment]
I got it running but nothing's apper...

http://prntscr.com/eqj7an

**Comment by ontofractal** [comment]
Have you managed to get it working? Glasnost needs 10-30 seconds to sync with blockchain after initialization.

**Comment by leagueofdelegates** [comment]
![image](https://cloud.githubusercontent.com/assets/18729195/24605077/a7c9b282-1867-11e7-931d-9a0abedd82ed.png)
I still have problem to run it on linux ubuntu server 16.10.

**Comment by ontofractal** [comment]
This is not a Glasnost bug. You have something else (perhaps another Glasnost instance) running on your web server on port 80. Therefore Glasnost can not listen on this port and errors on startup.

**Comment by leagueofdelegates** [comment]
![image](https://cloud.githubusercontent.com/assets/18729195/24616163/9d1ba416-1890-11e7-8498-6eb0832abc77.png)

Ok, apache2 was on port 80 so when i "sudo service apache2 stop" i was try to run docker with same comand and then i got this.

**Comment by ontofractal** [comment]
There is a `panic` error for `.go` files in your logs, so there seems to be something wrong with your docker engine. Perhaps an outdated version?

**Comment by leagueofdelegates** [comment]
I am using latest version of DOcker, same message appers on both OS Windows 10 and Ubuntu Server 16.10

**Comment by ontofractal** [comment]
Issue closed due to 2 weeks of inactivity
