### ISSUE TITLE
How to make changes to website html?

### ISSUE THREAD

**Issue by grctest** [cyberpunk-ventures/glasnost#8]
Hey,

So I've been trying to customize my website [beyondboinc](https://beyondboinc.net), specifically the [app.html.eex](https://github.com/grctest/glasnost/blob/master/lib/glasnost/web/templates/layout/app.html.eex) file.

I've managed to substitute this file for my own, but the changes are not shown.

I've tried resetting the nodejs server, but no luck.

Is there an easy way to make the docker container to recognize local file changes or to force the changed files to be used?

Will I have to make my own docker image?

Thanks, keep up the great work 👍

**Comment by ontofractal** [comment]
Yeah, you have to build your own docker image. Elixir/Erlang is a compiled language so you need to make changes before the compilation stage which is done during the docker image build step.

**Comment by grctest** [comment]
Ok, so it's not possible to recompile within the docker container?

I'll try to build my own docker image.

Thanks 👍

**Comment by grctest** [comment]
Ok, I managed to build my own docker image with changes.

>git clone repo
>cd reponame
>docker build .
> // Retrieve newly created docker image name
>docker run -d -it -p 8081:80 -e "GLASNOST_CONFIG_URL=https://github.com/grctest/glasnost/blob/master/config.ini" --restart on-failure:10 dockerimagename

Thanks for the pointers 👍
