### ISSUE TITLE
Images not using HTTPS

### ISSUE THREAD

**Issue by grctest** [cyberpunk-ventures/glasnost#9]
Hey,

I'm getting the following issue on my glasnost website:
![image](https://cloud.githubusercontent.com/assets/15861527/25315120/f917dc0a-2847-11e7-917f-1731687c835d.png)

Some of the posts by authors contain non-https image links, think we could somehow replace 'http' with 'https' when importing the data from the blockchain? 

Cheers 👍

**Comment by ontofractal** [comment]
Technically it's possible, but it would break links to image hosts that do not support SSL connections. I'm not sure this would be a good way to go forward.

**Comment by grctest** [comment]
Solved!
![image](https://cloud.githubusercontent.com/assets/15861527/25315504/c46aae96-284d-11e7-9c60-fccf96cbb6a8.png)

I added the following meta tag to the [layout template's head code](https://github.com/grctest/glasnost/blob/master/lib/glasnost/web/templates/layout/app.html.eex#L11):
> <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">

No need to manipulate the post's content 👍

**Comment by ontofractal** [comment]
That's a great idea, I'll look into implementing this as a config option.

**Comment by ontofractal** [comment]
implemented, can be activated in the config using `upgrade_insecure_requests: true`
